# Generated by Django 5.0.6 on 2026-09-30 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('overcrowding', 'Overcrowding Risk'), ('understaffing', 'Shift Understaffing'), ('long_wait', 'Long Wait-Time Patient')], max_length=32)),
                ('severity', models.CharField(choices=[('amber', 'Amber (Warning)'), ('red', 'Red (Critical)')], max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
