# Generated by Django 5.0.6 on 2026-09-30 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('is_on_duty', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='departments.department')),
            ],
            options={
                'ordering': ['-shift_start'],
            },
        ),
    ]
