# Generated by Django 5.0.6 on 2026-09-30 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffshift',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='staffshift',
            index=models.Index(fields=['department', 'is_on_duty'], name='staff_staff_departm_a16987_idx'),
        ),
    ]
