# Generated by Django 5.0.6 on 2026-09-30 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triage_level', models.CharField(choices=[('P1', 'P1 Critical (immediate)'), ('P2', 'P2 Urgent (within 30 min)'), ('P3', 'P3 Standard (within 2 hours)')], max_length=2)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_treatment', 'In Treatment'), ('discharged', 'Discharged')], default='waiting', max_length=20)),
                ('intake_time', models.DateTimeField(auto_now_add=True)),
                ('discharge_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-intake_time'],
            },
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('intake', 'Intake'), ('status_change', 'Status Change'), ('discharge', 'Discharge')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
