# Generated by Django 5.0.6 on 2026-09-30 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='departments.department'),
        ),
        migrations.AddField(
            model_name='queueevent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='queueevent',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['department', 'status'], name='patients_pa_departm_aa18e4_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['triage_level'], name='patients_pa_triage__d5d02c_idx'),
        ),
    ]
